/*
 * ennf2c.c - ENNF to C 源码转译器
 *
 * 将 .ennf 模型转换为独立可编译的纯 C 源码 (model.c + model.h)
 *
 * 使用方法:
 *   ennf2c <model.ennf> <output_dir>
 *
 * 输出:
 *   <output_dir>/model.h       - 接口头文件
 *   <output_dir>/model.c       - 模型实现 (静态 Arena + 内嵌权重 + 节点表)
 *   <output_dir>/main_test.c   - 测试入口
 *   <output_dir>/Makefile      - 编译脚本
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <sys/stat.h>
#include "../run_time/spinn_runtime.h"
#include "../run_time/spinn_memory_planner.h"

/* Stub: ennf2c 不需要执行推理, 只需要加载和规划。
 * 提供 spinn_dispatch_op 空实现避免链接 ops/ 目录全部源文件。 */
int spinn_dispatch_op(uint16_t op_type,
                      SpinnTensor **inputs, int n_in,
                      void *params, uint16_t params_size,
                      SpinnTensor **outputs, int n_out) {
    (void)op_type; (void)inputs; (void)n_in;
    (void)params; (void)params_size; (void)outputs; (void)n_out;
    return 0;
}

/* ============================================================
 * 工具函数
 * ============================================================ */
static void mkdir_p(const char *path) {
    struct stat st;
    if (stat(path, &st) == 0) return;
    char cmd[1024];
    snprintf(cmd, sizeof(cmd), "mkdir -p %s", path);
    if (system(cmd) != 0) {
        fprintf(stderr, "Failed to create directory: %s\n", path);
    }
}

/* 输出 C 字节数组（每行 16 字节） */
static void emit_byte_array(FILE *fp, const uint8_t *data, uint32_t size) {
    for (uint32_t i = 0; i < size; i++) {
        if (i % 16 == 0) fprintf(fp, "    ");
        fprintf(fp, "0x%02x", data[i]);
        if (i + 1 < size) fprintf(fp, ",");
        if ((i + 1) % 16 == 0 || i + 1 == size) fprintf(fp, "\n");
        else fprintf(fp, " ");
    }
}

/* ============================================================
 * 主转译流程
 * ============================================================ */
int main(int argc, char *argv[]) {
    if (argc < 3) {
        printf("Usage: %s <model.ennf> <output_dir>\n", argv[0]);
        printf("Generates model.c/model.h/main_test.c/Makefile\n");
        return 1;
    }

    const char *ennf_path = argv[1];
    const char *out_dir = argv[2];

    /* ===== 1. 加载 ENNF 模型 ===== */
    printf("[1/4] Loading ENNF: %s\n", ennf_path);
    SpinnContext *ctx = spinn_load(ennf_path);
    if (!ctx) {
        fprintf(stderr, "Failed to load %s\n", ennf_path);
        return 1;
    }
    printf("      Tensors=%u, Nodes=%u, Weights=%u\n",
           ctx->num_tensors, ctx->num_nodes, ctx->num_weights);

    /* ===== 2. 内存规划 (确定每个 FeatureMap 的 offset) ===== */
    printf("[2/4] Planning memory...\n");
    int peak = spinn_plan_memory(ctx, 0);
    if (peak < 0) {
        fprintf(stderr, "Memory planning failed: %d\n", peak);
        spinn_free(ctx);
        return 1;
    }
    uint32_t arena_size = (uint32_t)peak;
    printf("      Arena peak = %u bytes (%.2f KB)\n",
           arena_size, arena_size / 1024.0);

    /* ===== 3. 预加载所有权重 (用于内嵌生成) ===== */
    printf("[3/4] Loading weights...\n");
    for (uint32_t i = 0; i < ctx->num_tensors; i++) {
        SpinnTensor *t = &ctx->tensors[i];
        if (t->is_weight && t->size > 0) {
            t->data = spinn_get_weight(ctx, t->id);
            if (!t->data) {
                fprintf(stderr, "Failed to load weight tensor %u\n", t->id);
                spinn_free(ctx);
                return 1;
            }
        }
    }

    /* ===== 4. 生成代码 ===== */
    printf("[4/4] Generating C code to %s/...\n", out_dir);
    mkdir_p(out_dir);

    char path_buf[1024];

    /* ----- 4.1 model.h ----- */
    snprintf(path_buf, sizeof(path_buf), "%s/model.h", out_dir);
    FILE *fp = fopen(path_buf, "w");
    if (!fp) { fprintf(stderr, "Failed to open %s\n", path_buf); spinn_free(ctx); return 1; }

    fprintf(fp, "/* Auto-generated by ennf2c. DO NOT EDIT. */\n");
    fprintf(fp, "#ifndef __MODEL_H__\n#define __MODEL_H__\n\n");
    fprintf(fp, "#include <stdint.h>\n#include <stddef.h>\n\n");
    fprintf(fp, "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");
    fprintf(fp, "#define MODEL_NUM_TENSORS  %u\n", ctx->num_tensors);
    fprintf(fp, "#define MODEL_NUM_NODES    %u\n", ctx->num_nodes);
    fprintf(fp, "#define MODEL_NUM_WEIGHTS  %u\n", ctx->num_weights);
    fprintf(fp, "#define MODEL_ARENA_SIZE   %u\n", arena_size);
    fprintf(fp, "#define MODEL_NUM_INPUTS   %u\n", ctx->header.num_inputs);
    fprintf(fp, "#define MODEL_NUM_OUTPUTS  %u\n\n", ctx->header.num_outputs);

    /* 输入 tensor 信息 */
    SpinnTensor *t_in = &ctx->tensors[ctx->input_ids[0]];
    SpinnTensor *t_out = &ctx->tensors[ctx->output_ids[0]];
    fprintf(fp, "#define MODEL_INPUT_SIZE   %u  /* bytes */\n", t_in->size);
    fprintf(fp, "#define MODEL_INPUT_ELEMS  %u\n", t_in->elem_count);
    fprintf(fp, "#define MODEL_OUTPUT_SIZE  %u  /* bytes */\n", t_out->size);
    fprintf(fp, "#define MODEL_OUTPUT_ELEMS %u\n\n", t_out->elem_count);

    fprintf(fp, "/* 初始化模型 (设置 tensor 指针等, 调用一次即可) */\n");
    fprintf(fp, "void model_init(void);\n\n");
    fprintf(fp, "/* 执行推理: input/output 由调用者提供缓冲区 */\n");
    fprintf(fp, "int model_run(const void *input, void *output);\n\n");
    fprintf(fp, "#ifdef __cplusplus\n}\n#endif\n");
    fprintf(fp, "#endif /* __MODEL_H__ */\n");
    fclose(fp);
    printf("      [OK] model.h\n");

    /* ----- 4.2 model.c ----- */
    snprintf(path_buf, sizeof(path_buf), "%s/model.c", out_dir);
    fp = fopen(path_buf, "w");
    if (!fp) { spinn_free(ctx); return 1; }

    fprintf(fp, "/* Auto-generated by ennf2c. DO NOT EDIT. */\n");
    fprintf(fp, "#include \"model.h\"\n");
    fprintf(fp, "#include \"spinn_runtime.h\"\n");
    fprintf(fp, "#include \"spinn_ops.h\"\n");
    fprintf(fp, "#include <string.h>\n\n");

    /* 静态 Arena (16 字节对齐) */
    fprintf(fp, "/* ===== 静态 Arena (FeatureMap 池, 编译期确定大小) ===== */\n");
    fprintf(fp, "static uint8_t g_arena[MODEL_ARENA_SIZE] __attribute__((aligned(16)));\n\n");

    /* 内嵌权重数据：将所有权重连续放入 g_weights，记录每个 tensor 的偏移 */
    fprintf(fp, "/* ===== 内嵌权重 (static const, 编译期数据) ===== */\n");
    /* 计算总大小并分配映射表 */
    uint32_t total_w_size = 0;
    uint32_t *weight_off_in_blob = (uint32_t*)calloc(ctx->num_tensors, sizeof(uint32_t));
    for (uint32_t i = 0; i < ctx->num_tensors; i++) {
        SpinnTensor *t = &ctx->tensors[i];
        if (t->is_weight && t->size > 0) {
            /* 16 字节对齐 */
            total_w_size = (total_w_size + 15) & ~15;
            weight_off_in_blob[i] = total_w_size;
            total_w_size += t->size;
        } else {
            weight_off_in_blob[i] = 0xFFFFFFFFu;
        }
    }
    fprintf(fp, "#define MODEL_WEIGHTS_SIZE %u\n", total_w_size);
    fprintf(fp, "static const uint8_t g_weights[MODEL_WEIGHTS_SIZE] __attribute__((aligned(16))) = {\n");
    /* 拼接权重并输出 */
    uint8_t *blob = (uint8_t*)calloc(1, total_w_size);
    for (uint32_t i = 0; i < ctx->num_tensors; i++) {
        SpinnTensor *t = &ctx->tensors[i];
        if (t->is_weight && t->size > 0 && weight_off_in_blob[i] != 0xFFFFFFFFu) {
            memcpy(blob + weight_off_in_blob[i], t->data, t->size);
        }
    }
    emit_byte_array(fp, blob, total_w_size);
    free(blob);
    fprintf(fp, "};\n\n");

    /* Tensor 维度数组（dims）单独表 */
    fprintf(fp, "/* ===== Tensor 元数据 ===== */\n");
    fprintf(fp, "static SpinnTensor g_tensors[MODEL_NUM_TENSORS];\n\n");

    /* 节点参数：所有节点的 params 拼接进一个 blob */
    uint32_t total_p_size = 0;
    uint32_t *node_params_off = (uint32_t*)calloc(ctx->num_nodes, sizeof(uint32_t));
    for (uint32_t i = 0; i < ctx->num_nodes; i++) {
        SpinnNode *n = &ctx->nodes[i];
        node_params_off[i] = total_p_size;
        if (n->params_size > 0) {
            total_p_size += n->params_size;
            /* 4 字节对齐 */
            total_p_size = (total_p_size + 3) & ~3;
        }
    }
    fprintf(fp, "/* ===== 节点参数 blob ===== */\n");
    if (total_p_size > 0) {
        fprintf(fp, "static const uint8_t g_node_params[%u] = {\n", total_p_size);
        uint8_t *pblob = (uint8_t*)calloc(1, total_p_size);
        for (uint32_t i = 0; i < ctx->num_nodes; i++) {
            SpinnNode *n = &ctx->nodes[i];
            if (n->params_size > 0) {
                memcpy(pblob + node_params_off[i], n->params, n->params_size);
            }
        }
        emit_byte_array(fp, pblob, total_p_size);
        free(pblob);
        fprintf(fp, "};\n\n");
    } else {
        fprintf(fp, "static const uint8_t g_node_params[1] = {0};\n\n");
    }

    /* Node 数组 */
    fprintf(fp, "/* ===== 节点表 ===== */\n");
    fprintf(fp, "static SpinnNode g_nodes[MODEL_NUM_NODES];\n\n");

    /* 模型 IO ID */
    fprintf(fp, "/* ===== 模型输入/输出 ID ===== */\n");
    fprintf(fp, "static const uint16_t g_input_ids[MODEL_NUM_INPUTS] = {");
    for (uint16_t i = 0; i < ctx->header.num_inputs; i++) {
        fprintf(fp, " %u%s", ctx->input_ids[i], i + 1 < ctx->header.num_inputs ? "," : " ");
    }
    fprintf(fp, "};\n");
    fprintf(fp, "static const uint16_t g_output_ids[MODEL_NUM_OUTPUTS] = {");
    for (uint16_t i = 0; i < ctx->header.num_outputs; i++) {
        fprintf(fp, " %u%s", ctx->output_ids[i], i + 1 < ctx->header.num_outputs ? "," : " ");
    }
    fprintf(fp, "};\n\n");

    /* Tensor 元数据初始化表 (只读, 编译期常量) */
    fprintf(fp, "/* ===== Tensor 元数据初始化表 ===== */\n");
    fprintf(fp, "typedef struct {\n");
    fprintf(fp, "    uint16_t id;\n");
    fprintf(fp, "    uint8_t  dtype;\n");
    fprintf(fp, "    uint8_t  ndim;\n");
    fprintf(fp, "    uint32_t dims[8];\n");
    fprintf(fp, "    uint32_t elem_count;\n");
    fprintf(fp, "    uint32_t size;\n");
    fprintf(fp, "    uint32_t arena_offset;   /* 0xFFFFFFFF if not in arena */\n");
    fprintf(fp, "    uint32_t weight_offset;  /* 0xFFFFFFFF if not weight */\n");
    fprintf(fp, "    uint8_t  is_weight;\n");
    fprintf(fp, "    uint8_t  ref_count;\n");
    fprintf(fp, "} TensorInit;\n\n");
    fprintf(fp, "static const TensorInit g_tensor_init[MODEL_NUM_TENSORS] = {\n");
    for (uint32_t i = 0; i < ctx->num_tensors; i++) {
        SpinnTensor *t = &ctx->tensors[i];
        uint32_t arena_off = (t->is_weight || t->size == 0) ? 0xFFFFFFFFu : t->offset;
        uint32_t weight_off = (t->is_weight && t->size > 0) ? weight_off_in_blob[i] : 0xFFFFFFFFu;
        fprintf(fp, "    {%u, %u, %u, {", t->id, t->dtype, t->ndim);
        for (int d = 0; d < 8; d++) {
            fprintf(fp, "%u%s", t->dims[d], d < 7 ? "," : "");
        }
        fprintf(fp, "}, %u, %u, 0x%xu, 0x%xu, %u, %u},\n",
                t->elem_count, t->size, arena_off, weight_off,
                t->is_weight, t->ref_count);
    }
    fprintf(fp, "};\n\n");

    /* Node 元数据初始化表 */
    fprintf(fp, "/* ===== 节点初始化表 ===== */\n");
    fprintf(fp, "typedef struct {\n");
    fprintf(fp, "    uint16_t op_type;\n");
    fprintf(fp, "    uint8_t  num_inputs;\n");
    fprintf(fp, "    uint8_t  num_outputs;\n");
    fprintf(fp, "    uint16_t input_ids[8];\n");
    fprintf(fp, "    uint16_t output_ids[8];\n");
    fprintf(fp, "    uint16_t params_size;\n");
    fprintf(fp, "    uint32_t params_offset;\n");
    fprintf(fp, "} NodeInit;\n\n");
    fprintf(fp, "static const NodeInit g_node_init[MODEL_NUM_NODES] = {\n");
    for (uint32_t i = 0; i < ctx->num_nodes; i++) {
        SpinnNode *n = &ctx->nodes[i];
        fprintf(fp, "    {%u, %u, %u, {", n->op_type, n->num_inputs, n->num_outputs);
        for (int j = 0; j < 8; j++) {
            uint16_t v = (j < n->num_inputs) ? n->input_ids[j] : 0;
            fprintf(fp, "%u%s", v, j < 7 ? "," : "");
        }
        fprintf(fp, "}, {");
        for (int j = 0; j < 8; j++) {
            uint16_t v = (j < n->num_outputs) ? n->output_ids[j] : 0;
            fprintf(fp, "%u%s", v, j < 7 ? "," : "");
        }
        fprintf(fp, "}, %u, %u},\n", n->params_size, node_params_off[i]);
    }
    fprintf(fp, "};\n\n");

    /* model_init: 一次性初始化 */
    fprintf(fp, "/* ===== 初始化 ===== */\n");
    fprintf(fp, "static int g_initialized = 0;\n");
    fprintf(fp, "void model_init(void) {\n");
    fprintf(fp, "    if (g_initialized) return;\n");
    fprintf(fp, "    /* 初始化 tensor */\n");
    fprintf(fp, "    for (int i = 0; i < MODEL_NUM_TENSORS; i++) {\n");
    fprintf(fp, "        const TensorInit *ti = &g_tensor_init[i];\n");
    fprintf(fp, "        SpinnTensor *t = &g_tensors[i];\n");
    fprintf(fp, "        t->id = ti->id;\n");
    fprintf(fp, "        t->dtype = ti->dtype;\n");
    fprintf(fp, "        t->ndim = ti->ndim;\n");
    fprintf(fp, "        for (int d = 0; d < 8; d++) t->dims[d] = ti->dims[d];\n");
    fprintf(fp, "        t->elem_count = ti->elem_count;\n");
    fprintf(fp, "        t->is_weight = ti->is_weight;\n");
    fprintf(fp, "        t->ref_count = ti->ref_count;\n");
    fprintf(fp, "        t->size = ti->size;\n");
    fprintf(fp, "        t->offset = (ti->arena_offset == 0xFFFFFFFFu) ? 0 : ti->arena_offset;\n");
    fprintf(fp, "        if (ti->is_weight && ti->weight_offset != 0xFFFFFFFFu) {\n");
    fprintf(fp, "            t->data = (void*)(g_weights + ti->weight_offset);\n");
    fprintf(fp, "        } else if (ti->arena_offset != 0xFFFFFFFFu) {\n");
    fprintf(fp, "            t->data = g_arena + ti->arena_offset;\n");
    fprintf(fp, "        } else {\n");
    fprintf(fp, "            t->data = NULL;\n");
    fprintf(fp, "        }\n");
    fprintf(fp, "        t->packed_data = NULL;\n");
    fprintf(fp, "    }\n");
    fprintf(fp, "    /* 初始化 node */\n");
    fprintf(fp, "    for (int i = 0; i < MODEL_NUM_NODES; i++) {\n");
    fprintf(fp, "        const NodeInit *ni = &g_node_init[i];\n");
    fprintf(fp, "        SpinnNode *n = &g_nodes[i];\n");
    fprintf(fp, "        n->op_type = ni->op_type;\n");
    fprintf(fp, "        n->num_inputs = ni->num_inputs;\n");
    fprintf(fp, "        n->num_outputs = ni->num_outputs;\n");
    fprintf(fp, "        for (int j = 0; j < 8; j++) {\n");
    fprintf(fp, "            n->input_ids[j] = ni->input_ids[j];\n");
    fprintf(fp, "            n->output_ids[j] = ni->output_ids[j];\n");
    fprintf(fp, "        }\n");
    fprintf(fp, "        n->params_size = ni->params_size;\n");
    fprintf(fp, "        n->params = (ni->params_size > 0) ? (void*)(g_node_params + ni->params_offset) : NULL;\n");
    fprintf(fp, "    }\n");
    fprintf(fp, "    g_initialized = 1;\n");
    fprintf(fp, "}\n\n");

    /* model_run */
    fprintf(fp, "/* ===== 推理 ===== */\n");
    fprintf(fp, "int model_run(const void *input, void *output) {\n");
    fprintf(fp, "    if (!g_initialized) model_init();\n");
    fprintf(fp, "    /* 复制输入到第一个 input tensor */\n");
    fprintf(fp, "    SpinnTensor *t_in = &g_tensors[g_input_ids[0]];\n");
    fprintf(fp, "    if (input && t_in->data) memcpy(t_in->data, input, t_in->size);\n");
    fprintf(fp, "    /* 顺序执行节点 */\n");
    fprintf(fp, "    SpinnTensor *inputs[SPINN_MAX_IO];\n");
    fprintf(fp, "    SpinnTensor *outputs[SPINN_MAX_IO];\n");
    fprintf(fp, "    for (int i = 0; i < MODEL_NUM_NODES; i++) {\n");
    fprintf(fp, "        SpinnNode *node = &g_nodes[i];\n");
    fprintf(fp, "        for (int j = 0; j < node->num_inputs; j++)\n");
    fprintf(fp, "            inputs[j] = &g_tensors[node->input_ids[j]];\n");
    fprintf(fp, "        for (int j = 0; j < node->num_outputs; j++)\n");
    fprintf(fp, "            outputs[j] = &g_tensors[node->output_ids[j]];\n");
    fprintf(fp, "        spinn_dispatch_op(node->op_type, inputs, node->num_inputs,\n");
    fprintf(fp, "                          node->params, node->params_size,\n");
    fprintf(fp, "                          outputs, node->num_outputs);\n");
    fprintf(fp, "    }\n");
    fprintf(fp, "    /* 复制输出 */\n");
    fprintf(fp, "    SpinnTensor *t_out = &g_tensors[g_output_ids[0]];\n");
    fprintf(fp, "    if (output && t_out->data) memcpy(output, t_out->data, t_out->size);\n");
    fprintf(fp, "    return 0;\n");
    fprintf(fp, "}\n");

    fclose(fp);
    free(weight_off_in_blob);
    free(node_params_off);
    printf("      [OK] model.c (%u bytes weights, %u bytes node params)\n",
           total_w_size, total_p_size);

    /* ----- 4.3 main_test.c ----- */
    snprintf(path_buf, sizeof(path_buf), "%s/main_test.c", out_dir);
    fp = fopen(path_buf, "w");
    if (fp) {
        fprintf(fp, "/* Auto-generated test entry by ennf2c */\n");
        fprintf(fp, "#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n#include <time.h>\n");
        fprintf(fp, "#include \"model.h\"\n\n");
        fprintf(fp, "static double now_ms(void) {\n");
        fprintf(fp, "    struct timespec ts; clock_gettime(CLOCK_MONOTONIC, &ts);\n");
        fprintf(fp, "    return ts.tv_sec * 1000.0 + ts.tv_nsec / 1e6;\n");
        fprintf(fp, "}\n\n");
        fprintf(fp, "int main(int argc, char *argv[]) {\n");
        fprintf(fp, "    /* 准备输入 (与 SPINN runtime 一致, 测试用) */\n");
        fprintf(fp, "    float *input = (float*)malloc(MODEL_INPUT_SIZE);\n");
        fprintf(fp, "    float *output = (float*)malloc(MODEL_OUTPUT_SIZE);\n");
        fprintf(fp, "    for (uint32_t i = 0; i < MODEL_INPUT_ELEMS; i++) input[i] = (float)i / 1000.0f;\n\n");
        fprintf(fp, "    double t0 = now_ms();\n");
        fprintf(fp, "    model_init();\n");
        fprintf(fp, "    double t_init = now_ms() - t0;\n\n");
        fprintf(fp, "    t0 = now_ms();\n");
        fprintf(fp, "    model_run(input, output);\n");
        fprintf(fp, "    double t_run = now_ms() - t0;\n\n");
        fprintf(fp, "    fprintf(stderr, \"Init: %%.2fms, Run: %%.2fms\\n\", t_init, t_run);\n");
        fprintf(fp, "    fprintf(stderr, \"Arena: %%u bytes\\n\", (uint32_t)MODEL_ARENA_SIZE);\n");
        fprintf(fp, "    printf(\"Generated Result: \");\n");
        fprintf(fp, "    int n = (MODEL_OUTPUT_ELEMS > 10) ? 10 : MODEL_OUTPUT_ELEMS;\n");
        fprintf(fp, "    for (int i = 0; i < n; i++) printf(\"%%.6f \", output[i]);\n");
        fprintf(fp, "    printf(\"\\n\");\n");
        fprintf(fp, "    free(input); free(output);\n");
        fprintf(fp, "    return 0;\n");
        fprintf(fp, "}\n");
        fclose(fp);
        printf("      [OK] main_test.c\n");
    }

    /* ----- 4.4 Makefile ----- */
    snprintf(path_buf, sizeof(path_buf), "%s/Makefile", out_dir);
    fp = fopen(path_buf, "w");
    if (fp) {
        fprintf(fp, "# Auto-generated Makefile by ennf2c\n");
        fprintf(fp, "# Reuses SPINN runtime ops library for now (Phase B)\n\n");
        fprintf(fp, "CC = gcc\n");
        fprintf(fp, "# RT: SPINN runtime root. Override with: make RT=/path/to/run_time\n");
        fprintf(fp, "RT ?= ../../run_time\n");
        fprintf(fp, "CFLAGS = -Wall -O2 -I. -I$(RT) -I$(RT)/.. -mavx2 -mfma -fopenmp\n");
        fprintf(fp, "LDFLAGS = -lm -lpthread -fopenmp\n\n");
        fprintf(fp, "OPS = $(wildcard $(RT)/ops/activation/*.c) \\\n");
        fprintf(fp, "      $(wildcard $(RT)/ops/math/*.c) \\\n");
        fprintf(fp, "      $(wildcard $(RT)/ops/trig/*.c) \\\n");
        fprintf(fp, "      $(wildcard $(RT)/ops/conv/*.c) \\\n");
        fprintf(fp, "      $(wildcard $(RT)/ops/pool/*.c) \\\n");
        fprintf(fp, "      $(wildcard $(RT)/ops/norm/*.c) \\\n");
        fprintf(fp, "      $(wildcard $(RT)/ops/mm/*.c) \\\n");
        fprintf(fp, "      $(wildcard $(RT)/ops/shape/*.c) \\\n");
        fprintf(fp, "      $(wildcard $(RT)/ops/reduce/*.c) \\\n");
        fprintf(fp, "      $(wildcard $(RT)/ops/tensor/*.c) \\\n");
        fprintf(fp, "      $(wildcard $(RT)/ops/rnn/*.c) \\\n");
        fprintf(fp, "      $(wildcard $(RT)/ops/control/*.c)\n");
        fprintf(fp, "ASM = $(RT)/ops/mm/gemm_kernel_avx2_asm.S\n\n");
        fprintf(fp, "RT_SRCS = $(RT)/spinn_ops.c $(RT)/spinn_threadpool.c\n\n");
        fprintf(fp, "TARGET = model_run\n\n");
        fprintf(fp, "all: $(TARGET)\n\n");
        fprintf(fp, "$(TARGET): model.c main_test.c $(RT_SRCS) $(OPS) $(ASM)\n");
        fprintf(fp, "\t$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)\n\n");
        fprintf(fp, "clean:\n");
        fprintf(fp, "\trm -f $(TARGET)\n\n");
        fprintf(fp, ".PHONY: all clean\n");
        fclose(fp);
        printf("      [OK] Makefile\n");
    }

    spinn_free(ctx);
    printf("\nDone. Build with: cd %s && make\n", out_dir);
    return 0;
}
